"""Limatus: a diagnose-and-steer quality loop for AI-generated content."""

__version__ = "0.14.1"

from .sdk import (
    AnnotationFormatError,
    EditorialDiagnosisValidationError,
    EditorialLoopValidationError,
    EditorialOptionsValidationError,
    LoadedStyleProfile,
    StyleProfileValidationError,
    candidates_from_options,
    compare,
    compose_loop_record,
    diagnose,
    scan,
    verify,
    check_rules,
    check_standfirst,
    generate_options,
    suggest_rewrite,
    generate_suggestions,
    load_config,
    preview_patch_text,
    record_decision,
    render_annotations,
)

__all__ = [
    "AnnotationFormatError",
    "EditorialDiagnosisValidationError",
    "EditorialLoopValidationError",
    "EditorialOptionsValidationError",
    "LoadedStyleProfile",
    "StyleProfileValidationError",
    "__version__",
    "candidates_from_options",
    "compare",
    "compose_loop_record",
    "diagnose",
    "preview_patch_text",
    "scan",
    "verify",
    "check_rules",
    "check_standfirst",
    "generate_options",
    "suggest_rewrite",
    "generate_suggestions",
    "load_config",
    "record_decision",
    "render_annotations",
]
